package com.gyosanila.kartcilik.ui

import androidx.compose.runtime.staticCompositionLocalOf

/** Semua teks UI — ganti bahasa lewat Pengaturan (id/en). */
data class AppStrings(
    // Menu & splash
    val appName: String,
    val splashSub: String,
    val menuPick: String,
    val playCar: String,
    val playCarDesc: String,
    val playFruit: String,
    val playFruitDesc: String,
    val settings: String,
    val offlineTag: String,
    // Kontrol
    val cmdForward: String,
    val cmdLeft: String,
    val cmdRight: String,
    val cmdPick: String,
    val cmdPlay: String,
    val cmdReset: String,
    val hintStripCar: String,
    val hintStripFruit: String,
    val deleteOne: String,
    val clearAll: String,
    val prev: String,
    val next: String,
    val sound: String,
    // Level & reward
    val level: String,
    val levelNext: String,
    val playAgain: String,
    val winNoneTitle: String,
    val winNoneSub: String,
    val winSmallTitle: String,
    val winSmallSub: String,
    val winBigTitle: String,
    val winBigSub: String,
    // Dialog buah
    val crashTitle: String,
    val crashMsg: String,
    val retry: String,
    val exhaustedTitle: String,
    val exhaustedMsg: String,
    val keepBuilding: String,
    // Pengaturan
    val settingsTitle: String,
    val langLabel: String,
    val langId: String,
    val langEn: String,
    val controllerLabel: String,
    val controllerKart: String,
    val controllerSimple: String,
    val timerLabel: String,
    val timerOff: String,
    val timerMin: String,
    val timerNote: String,
    // Timer istirahat
    val breakTitle: String,
    val breakMsg: String,
    val breakContinue: String,
    // Lock & pujian rating
    val keepPlaying: String,
    val lockAsk: String,
    val praise1: String,
    val praise2: String,
    val praise3: String,
    val praise4: String,
    val praise5: String,
    // Shadow preview
    val shadowLabel: String,
    val shadowOn: String,
    val shadowOff: String,
)

val StringsId = AppStrings(
    appName = "Logichild",
    splashSub = "Belajar logika sambil main!",
    menuPick = "Pilih game-nya!",
    playCar = "Main Mobil",
    playCarDesc = "Susun langkah, mobil sampai finish!",
    playFruit = "Petik Buah",
    playFruitDesc = "Susun perintah, robot panen buah!",
    settings = "Pengaturan",
    offlineTag = "Tanpa internet • Untuk balita 3+",
    cmdForward = "Maju",
    cmdLeft = "Kiri",
    cmdRight = "Kanan",
    cmdPick = "Petik",
    cmdPlay = "Main!",
    cmdReset = "Ulang",
    hintStripCar = "susun langkah di sini 👇",
    hintStripFruit = "susun perintah di bawah 👇",
    deleteOne = "Hapus satu",
    clearAll = "Hapus semua",
    prev = "Mundur",
    next = "Maju",
    sound = "Suara",
    level = "Level",
    levelNext = "Level berikutnya ▶",
    playAgain = "Main lagi",
    winNoneTitle = "Level %1\$d Selesai!",
    winNoneSub = "Keren! Lanjut ya!",
    winSmallTitle = "🎉 LEVEL %1\$d!",
    winSmallSub = "Hebat! Semakin jago! 👏",
    winBigTitle = "🎉🎉 LEVEL %1\$d!",
    winBigSub = "LUAR BIASA! 10 level beres! 👏👏👏",
    crashTitle = "💥 Ups!",
    crashMsg = "Robot nabrak batu! Ayo susun ulang perintahnya.",
    retry = "Coba Lagi 🔄",
    exhaustedTitle = "🤔 Belum Selesai",
    exhaustedMsg = "Masih ada buah yang belum dipetik. Tambah blok perintah, robot balik ke awal lagi.",
    keepBuilding = "Lanjut Susun ➕",
    settingsTitle = "Pengaturan",
    langLabel = "Bahasa",
    langId = "Indonesia",
    langEn = "English",
    controllerLabel = "Tipe Kontrol",
    controllerKart = "Tombol Bulat",
    controllerSimple = "Tombol Kotak",
    timerLabel = "Timer Layar",
    timerOff = "Mati",
    timerMin = "%1\$d menit",
    timerNote = "Anak istirahat otomatis setelah durasi bermain.",
    breakTitle = "Waktunya Istirahat 💤",
    breakMsg = "Waktu bermain sudah habis, teman. Yuk istirahat dulu!",
    breakContinue = "Lanjut",
    keepPlaying = "Main Lagi ▶",
    lockAsk = "Minta tolong orang tua ya 🙏",
    praise1 = "Tetap semangat! Coba lagi ya! 💪",
    praise2 = "Bagus! Coba lebih hemat langkah!",
    praise3 = "Keren! Terus berlatih ya!",
    praise4 = "Hebat! Hampir sempurna!",
    praise5 = "Luar biasa! Sempurna! 👏👏👏",
    shadowLabel = "Bayangan Preview",
    shadowOn = "Aktif (level 1-5)",
    shadowOff = "Mati",
)

val StringsEn = AppStrings(
    appName = "Logichild",
    splashSub = "Learn logic while playing!",
    menuPick = "Pick a game!",
    playCar = "Car Race",
    playCarDesc = "Arrange steps, get the car to the finish!",
    playFruit = "Fruit Picking",
    playFruitDesc = "Arrange commands, robot picks the fruits!",
    settings = "Settings",
    offlineTag = "No internet • For toddlers 3+",
    cmdForward = "Forward",
    cmdLeft = "Left",
    cmdRight = "Right",
    cmdPick = "Pick",
    cmdPlay = "GO!",
    cmdReset = "Reset",
    hintStripCar = "arrange steps here 👇",
    hintStripFruit = "arrange commands below 👇",
    deleteOne = "Delete one",
    clearAll = "Clear all",
    prev = "Back",
    next = "Next",
    sound = "Sound",
    level = "Level",
    levelNext = "Next level ▶",
    playAgain = "Play again",
    winNoneTitle = "Level %1\$d Done!",
    winNoneSub = "Awesome! Keep going!",
    winSmallTitle = "🎉 LEVEL %1\$d!",
    winSmallSub = "Great! Getting better! 👏",
    winBigTitle = "🎉🎉 LEVEL %1\$d!",
    winBigSub = "AMAZING! 10 levels done! 👏👏👏",
    crashTitle = "💥 Oops!",
    crashMsg = "The robot hit a rock! Let's rearrange the commands.",
    retry = "Try Again 🔄",
    exhaustedTitle = "🤔 Not Finished",
    exhaustedMsg = "Some fruits are still left. Add more command blocks, the robot goes back to start.",
    keepBuilding = "Keep Building ➕",
    settingsTitle = "Settings",
    langLabel = "Language",
    langId = "Indonesian",
    langEn = "English",
    controllerLabel = "Controller Type",
    controllerKart = "Round Buttons",
    controllerSimple = "Square Buttons",
    timerLabel = "Screen Timer",
    timerOff = "Off",
    timerMin = "%1\$d minutes",
    timerNote = "Child gets an auto break after play duration.",
    breakTitle = "Time to Rest 💤",
    breakMsg = "Play time is over, buddy. Let's take a break!",
    breakContinue = "Continue",
    keepPlaying = "Keep Playing ▶",
    lockAsk = "Ask your parents for help 🙏",
    praise1 = "Keep going! Try again! 💪",
    praise2 = "Nice! Try fewer steps!",
    praise3 = "Cool! Keep practicing!",
    praise4 = "Great! Almost perfect!",
    praise5 = "Amazing! Perfect! 👏👏👏",
    shadowLabel = "Shadow Preview",
    shadowOn = "On (levels 1-5)",
    shadowOff = "Off",
)

val LocalStrings = staticCompositionLocalOf { StringsId }
